brand_names = [
'Greylock',
'Trinity Ventures',
'Benchmark',
'Foundation Capital',
'Floodgate',
'Lowercase Capital',
'Accel',
'Sequoia Capital',
'Redpoint',
'Kleiner Perkins',
'GV',
'Lightspeed Venture Partners',
'First Round Capital',
'Foundry Group',
'General Catalyst',
'True Ventures',
'Founders Fund',
'Andreessen Horowitz',
'Union Square Ventures',
'Felicis Ventures',
'Battery Ventures',
'CRV',
'Menlo Ventures',
'Mayfield Fund',
'DCVC',
'New Enterprise Associates',
'Lux Capital',
'Khosla Ventures',
'Intel Capital',
'Paul Graham',
'Elad Gil',
'Eric Ries',
]