[
'Series G', 
'Series F', 
'Initial Coin Offering', 
'Post-IPO Debt',
'Secondary Market', 
'Series I', 
'Series J', 
'Series H',
'Equity Crowdfunding', 
'Post-IPO Secondary',
'Product Crowdfunding', 
'Grant', 
'Series A', 
'Series B',
'Series C', 
'Series D',
'Series E', 
'Seed Round',
'Angel Round',
'Funding Round', 
'Venture Round', 
'Debt Financing',
'Pre Seed Round', 
'Corporate Round', 
'Post-IPO Equity',
'Convertible Note',
'Private Equity Round',
'Non Equity Assistance'
]