some_investors = [
'Bill Gates', 
'Ridge Ventures',
'Peter Thiel', 
'Y Combinator', 
"M12 - Microsoft's Venture Fund", 
'Redpoint eventures', 
'WestWave Capital',
'Earlybird Venture Capital', 
'Commerce Ventures', 
'500 Startups', 
'Oceans', 
'Techstars', 
'500 Istanbul',
]